/// <reference path="../typings/codePush.d.ts" />

"use strict";

import { FilesystemDirectory, FilesystemEncoding, Plugins } from "@capacitor/core";

const { Filesystem } = Plugins;

/**
 * File utilities for CodePush.
 */
class FileUtil {
    public static async directoryExists(directory: FilesystemDirectory, path: string, callback: Callback<boolean>): Promise<void> {
        try {
            const statResult = await Filesystem.stat({directory, path});
            callback(null, statResult.type === "directory");
        } catch (error) {
            callback(null, false);
        }
    }

    public static fileErrorToError(fileError: FileError, message?: string): Error {
        return new Error((message ? message : "An error has occurred while performing the operation. ") + " Error code: " + fileError.code);
    }

    public static getDataDirectory(path: string, createIfNotExists: boolean, callback: Callback<string>): void {
        FileUtil.getDirectory(FilesystemDirectory.Data, path, createIfNotExists, callback);
    }

    public static writeStringToDataFile(content: string, path: string, createIfNotExists: boolean, callback: Callback<void>): void {
        FileUtil.writeStringToFile(content, FilesystemDirectory.Data, path, createIfNotExists, callback);
    }

    public static getApplicationDirectory(path: string, callback: Callback<DirectoryEntry>): void {
        FileUtil.getApplicationEntry<DirectoryEntry>(path, callback);
    }

    public static getOrCreateFile(parent: DirectoryEntry, path: string, createIfNotExists: boolean, success: (result: FileEntry) => void, fail: (error: FileError) => void): void {
        var failFirst = (error: FileError) => {
            if (!createIfNotExists) {
                fail(error);
            } else {
                parent.getFile(path, { create: true, exclusive: false }, success, fail);
            }
        };

        /* check if the file exists first - getFile fails if the file exists and the create flag is set to true */
        parent.getFile(path, { create: false, exclusive: false }, success, failFirst);
    }

    public static getFile(fsDir: FilesystemDirectory, path: string, fileName: string, createIfNotExists: boolean, callback: Callback<FileEntry>): void {
        FileUtil.getDirectory(fsDir, path, createIfNotExists, (error: Error, directoryEntry: DirectoryEntry) => {
            if (error) {
                callback(error, null);
            } else {
                FileUtil.getOrCreateFile(directoryEntry, fileName, createIfNotExists,
                    (entry: FileEntry) => { callback(null, entry); },
                    (error: FileError) => { callback(FileUtil.fileErrorToError(error), null); });
            }
        });
    }

    public static getDataFile(path: string, fileName: string, createIfNotExists: boolean, callback: Callback<FileEntry>): void {
        FileUtil.getFile(FilesystemDirectory.Data, path, fileName, createIfNotExists, callback);
    }

    public static async fileExists(directory: FilesystemDirectory, path: string, callback: Callback<boolean>): Promise<void> {
        try {
            const statResult = await Filesystem.stat({directory, path});
            callback(null, statResult.type === "file");
        } catch (error) {
            callback(null, false);
        }
    }

    /**
     * Gets a DirectoryEntry based on a path.
     */
    public static async getDirectory(fsDir: FilesystemDirectory, path: string, createIfNotExists: boolean, callback: Callback<string>): Promise<void> {
        try {
            const appDir = await Filesystem.getUri({directory: fsDir, path});
            callback(null, appDir.uri);
            return;
        } catch (error) {
            if (!createIfNotExists) {
                callback(new Error("Could not get application subdirectory. Error code: " + error.code), null);
                return;
            }
        }

        // directory does not exist so we need to create it
        try {
            await Filesystem.mkdir({directory: fsDir, path, createIntermediateDirectories: true})
            const appDir = await Filesystem.getUri({directory: fsDir, path});
            callback(null, appDir.uri);
        } catch (error) {
            callback(new Error("Could not create application subdirectory. Error code: " + error.code), null);
        }
    }

    public static dataDirectoryExists(path: string, callback: Callback<boolean>): void {
        FileUtil.directoryExists(FilesystemDirectory.Data, path, callback);
    }

    public static copyDirectoryEntriesTo(sourceDir: DirectoryEntry, destinationDir: DirectoryEntry, ignoreList: string[], callback: Callback<void>): void {
        /*
            Native-side exception occurs while trying to copy “.DS_Store” and “__MACOSX” entries generated by macOS, so just skip them
        */
        if (ignoreList.indexOf(".DS_Store") === -1){
            ignoreList.push(".DS_Store");
        }
        if (ignoreList.indexOf("__MACOSX") === -1){
            ignoreList.push("__MACOSX");
        }

        var fail = (error: FileError) => {
            callback(FileUtil.fileErrorToError(error), null);
        };

        var success = (entries: Entry[]) => {
            var i = 0;

            var copyOne = () => {
                if (i < entries.length) {
                    var nextEntry = entries[i++];
                    /* recursively call copyOne on copy success */
                    if (ignoreList.indexOf(nextEntry.name) > 0) {
                        copyOne();
                    } else {
                        var entryAlreadyInDestination = (destinationEntry: Entry) => {
                            var replaceError = (fileError: FileError) => {
                                callback(new Error("Error during entry replacement. Error code: " + fileError.code), null);
                            };

                            if (destinationEntry.isDirectory) {
                                /* directory */
                                FileUtil.copyDirectoryEntriesTo(<DirectoryEntry>nextEntry, <DirectoryEntry>destinationEntry, ignoreList, (error: Error) => {
                                    if (error) {
                                        callback(error, null);
                                    } else {
                                        copyOne();
                                    }
                                });
                            } else {
                                /* file */
                                var fileEntry = <FileEntry>destinationEntry;
                                fileEntry.remove(() => {
                                    nextEntry.copyTo(destinationDir, nextEntry.name, copyOne, fail);
                                }, replaceError);
                            }
                        };

                        var entryNotInDestination = (error: FileError) => {
                            /* just copy directory to destination */
                            nextEntry.copyTo(destinationDir, nextEntry.name, copyOne, fail);
                        };

                        FileUtil.entryExistsInDirectory(nextEntry, destinationDir, entryAlreadyInDestination, entryNotInDestination);
                    }
                } else {
                    /* copied all successfully */
                    callback(null, null);
                }
            };

            copyOne();
        };

        var directoryReader = sourceDir.createReader();
        directoryReader.readEntries(success, fail);
    }

    /**
     * Checks if an entry already exists in a given directory.
     */
    public static entryExistsInDirectory(entry: Entry, destinationDir: DirectoryEntry, exists: SuccessCallback<Entry>, doesNotExist: { (error: FileError): void; }): void {
        var options: Flags = { create: false, exclusive: false };

        if (entry.isDirectory) {
            destinationDir.getDirectory(entry.name, options, exists, doesNotExist);
        } else {
            destinationDir.getFile(entry.name, options, exists, doesNotExist);
        }
    }

    /**
     * Recursively deletes the contents of a directory.
     */
    public static async deleteDirectory(path: string, deleteDirCallback: Callback<void>) {
        try {
            await Filesystem.rmdir({directory: FilesystemDirectory.Data, path})
            deleteDirCallback(null, null);
        } catch (error) {
            deleteDirCallback(error, null);
        }
    }

    /**
     * Deletes a given set of files from a directory.
     */
    public static deleteEntriesFromDataDirectory(dirPath: string, filesToDelete: string[], callback: Callback<void>): void {
        FileUtil.getDataDirectory(dirPath, false, (error: Error, rootDir: DirectoryEntry) => {
            if (error) {
                callback(error, null);
            } else {
                var i = 0;

                var deleteOne = () => {
                    if (i < filesToDelete.length) {
                        var continueDeleting = () => {
                            i++;
                            deleteOne();
                        };

                        var fail = (error: FileError) => {
                            console.log("Could not delete file: " + filesToDelete[i]);
                            /* If delete fails, silently continue */
                            continueDeleting();
                        };

                        var success = (entry: FileEntry) => {
                            entry.remove(continueDeleting, fail);
                        };

                        rootDir.getFile(filesToDelete[i], { create: false, exclusive: false }, success, fail);
                    } else {
                        callback(null, null);
                    }
                };

                deleteOne();
            }
        });
    }

    /**
     * Writes a string to a file.
     */
    public static async writeStringToFile(data: string, directory: FilesystemDirectory, path: string, createIfNotExists: boolean, callback: Callback<void>): Promise<void> {
        try {
            await Filesystem.writeFile({directory, path, data, encoding: FilesystemEncoding.UTF8})
            callback(null, null);
        } catch(error) {
            callback(new Error("Could write the current package information file. Error code: " + error.code), null);
        }
    }

    public static readFileEntry(fileEntry: FileEntry, callback: Callback<string>): void {
        fileEntry.file((file: File) => {
            var fileReader = new FileReader();
            fileReader.onloadend = (ev: any) => {
                callback(null, ev.target.result);
            };

            fileReader.onerror = (ev: any) => {
                callback(new Error("Could not get file. Error: " + ev.error), null);
            };

            fileReader.readAsText(file);
        }, (error: FileError) => {
            callback(new Error("Could not get file. Error code: " + error.code), null);
        });
    }

    public static async readFile(directory: FilesystemDirectory, path: string, callback: Callback<string>): Promise<void> {
        try{
            const result = await Filesystem.readFile({directory, path, encoding: FilesystemEncoding.UTF8});
            callback(null, result.data);
        } catch (error) {
            callback(error, null);
        }
    }

    public static readDataFile(path: string, callback: Callback<string>): void {
        FileUtil.readFile(FilesystemDirectory.Data, path, callback);
    }

    private static getApplicationEntry<T extends Entry>(path: string, callback: Callback<T>): void {
        var success = (entry: T) => {
            callback(null, entry);
        };

        var fail = (error: FileError) => {
            callback(FileUtil.fileErrorToError(error), null);
        };

        // TODO: implement me
        window.resolveLocalFileSystemURL(cordova.file.applicationDirectory + path, success, fail);
    }
}

export = FileUtil;
